[build]
  publish = "out"
  command = "npm run build-prod"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "altalya"
  deliveryType = "upload"
  imagesPath = "/public"
